version: '2'
services:
    gestc-app:
        image: gestc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestc-mysql:3306/gestc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gestc-elasticsearch:9300
        ports:
            - 8080:8080
    gestc-mysql:
        extends:
            file: mysql.yml
            service: gestc-mysql
    gestc-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gestc-elasticsearch
